# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Surya Aravind Maddula
title: Computer Science Student
email: surya10497@gmail.com
website: suryaaravind97.github.io

# Social links
twitter_username: suryaaravind1 
github_username: suryaaravind97
# dribbble_username: jekyll
#facebook_username: https://twitter.com/suryaaravind1
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: Surya Aravind
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Surya Aravind and I'm a Final year Computer Science Student. I have done internship at trillion It solutions

  I am most skilled in:  <mark>java</mark> and <mark>Web Development</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Worked as  Resident Assistant in my 3rd year My role is to manage a university residence hall floor of ethnically diverse freshman students in Psychological and academic aspects.

  Secured 2nd position in HackBMU Hackathon, built a gesture-based chat bot that allows speech and hearing impaired users to interact using signed language.
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
